### ISSUE TITLE
How run Hapless with python 3 scripts? 

### ISSUE THREAD

**Issue by ReneFroger** [bmwant/hapless#2]
First, thanks for creating this nice tool! It's really useful for my workflow.

However, lately literally all python processes uses python 3 as interpreter. For example, when I want to use to run [Django](https://www.djangoproject.com/) server I usually use the command: `python manage.py runserver`.

This works fine. But with hap: `hap run --check python manage.py runserver` gives me the error:

```
🧲 Hap exited too quickly. stderr message:
  File "manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax

```
Any suggestions to let this work with python 3 scripts?

**Comment by ReneFroger** [comment]
Edited: Nevermind, I got it solved.

Just call python3 within hap command.

**Comment by bmwant** [comment]
@ReneFroger thanks, I'm really happy that this tool is useful for somebody. Another way of solving this should be by providing full path to python exec within the command
```bash
$ which python3
# /home/user/.pyenv/shims/python3
$ hap run -- /home/user/.pyenv/shims/python3 my_script.py
```

But this issue indicates another problem that you highlight #4 here, so I'll be looking into that anyway.

Just a side note:
when running commands such as django server or similar I suggest you to use fully-fledged process management tools like [Supervisor](http://supervisord.org/), [pm2](https://pm2.keymetrics.io/) or [forever](https://github.com/foreversd/forever). For the local development it's totally ok to use hapless, but do not consider it for production as basically it's just an improved version of `nohup`.
