### ISSUE TITLE
License of this Project

### ISSUE THREAD

**Issue by xzyaoi** [bmwant/hapless#23]
Hi,

Thanks for this amazing project! It looks very promising and I want to slightly extend/modify some parts to fit my need.

I am wondering about the license for this project. Is it allowed if I use part of it in my project?

Best regards,
Xiaozhe

**Comment by bmwant** [comment]
Hi @xzyaoi , feel free to open PR with the change to the repo - I'm actively developing it, so the process of adding new features should be pretty quick.

You can reuse any of the code in your own project without any issues - go ahead if needed.

**Comment by bmwant** [comment]
The license is https://tldrlegal.com/license/mit-license MIT

**Comment by xzyaoi** [comment]
@bmwant Many thanks for your swift reply!
