### ISSUE TITLE
Specificy a custom aliases for process? 

### ISSUE THREAD

**Issue by ReneFroger** [bmwant/hapless#3]
Personally when I run a process in the background, I find the the aliases assigned by Hapless, like `hap-17pqkr` or something, not very obvious. When I run multiple processes, I can be easily lost to figure out which process I need to inspect.

Would it be possible to assign a alias name for it like: `hap --aliases docker run docker-compose-up` ? 

(By the way: stay strong in Ukraïne, slava Ukraini!)

**Comment by bmwant** [comment]
Hey @ReneFroger !
It' already possible to use alias name

```bash
$ hap run --name long -- python ./examples/long_running.py
# or in your case
$ hap run --name docker docker run docker-compose-up
# a little more explicit (to separate you command and happless parameters)
$ hap run --name docker -- docker run docker-compose-up
```

In case you don't have this feature please upgrade to the latest version
```bash
$ pip install --upgrade hapless
```

Also [see docs](https://github.com/bmwant/hapless/blob/main/USAGE.md) for reference on usage.

Thanks for your support
