### ISSUE TITLE
Bug: First failed log not being cleaned

### ISSUE THREAD

**Issue by josht000** [bmwant/hapless#34]
Before `hap clean`:

![image](https://github.com/user-attachments/assets/b10bbb7d-e411-44e5-8561-50c212fc38f3)

After `hap clean`: 

![image](https://github.com/user-attachments/assets/c32e9a58-ad8d-4ba6-b8b4-1c2fcb0daf94)

ls on the tmp folder for that hap log:
![image](https://github.com/user-attachments/assets/aaf8a023-bcfd-4604-bf1a-0d9fdb254482)

❯ hap --version
hapless, version 0.4.1

**Suggested Fix:** if the rc file is not present, don't give up cleaning out the temp hap directory. Just follow through and delete the dir. Also watch out for folders owned by another user, they can cause stack traces as well.

**Comment by josht000** [comment]
Not a bug! Actually, your new version has a new functionality and needs the cleanall param. hmm

**Comment by bmwant** [comment]
@josht000 the idea behind this is to retain failed logs and status to be able to inspect/debug what went wrong. By default `clean` removes only successfully completes ones as likely you don't need to track them anymore.

`hap clean --all`
or
`hap cleanall` 

will remove all finished processes (both failed and successful) and keep only running ones
