### ISSUE TITLE
Auto Restart process feature?

### ISSUE THREAD

**Issue by mohitjoshi155** [bmwant/hapless#35]
Auto Restart process feature?

**Comment by bmwant** [comment]
@mohitjoshi155 could you elaborate on that?
* what are the restart criteria? non-zero exit code? failure after some timeout?
* should we have some amount of retries or trying forever until success?
* what the invocation would look like? `--restart`/`--retry`?

Can you also describe a specific use-case you are facing when this functionality is needed?

Note, that for proper process management you should use tools like [Monit](https://mmonit.com/monit/) or [supervisor](http://supervisord.org/) which have this functionality already

**Comment by mohitjoshi155** [comment]
i wanted it to restart process on system reboot automatically 
yes restart flag would be good enough
retry limit can be default 3 times on failure
i use docker containers they have this feature i found it missing here

**Comment by fpankretic** [comment]
If I may jump in with a suggestion. What I found in my workflow is that often my code gets updated then I need to manually execute same set of commands:

`
hap run -n _name_ -- _some script_
(after some time...)
git pull
hap kill N
hap cleanall
hap run -n _name_ -- _some script_
`

Ofc. this would all be solvable with start script, but It would be great that there is a command like `hap restart N` where it just kills the process and starts it again with original parameters. Not sure if this is something that OP had in mind.

**Comment by bmwant** [comment]
Feature was merged and released as a new `0.5.0` version.
