### ISSUE TITLE
Catch exception, permission denied

### ISSUE THREAD

**Issue by josht000** [bmwant/hapless#36]
when another user on a shared system runs hapless it does what it's supposed to and puts logs in the /tmp/hapless folder with the correct folder permissions. 

The problem comes when we try and run hap clean or hap cleanall. A stack trace is spit out and the program crashes, leaving some of my hap logs still in there. 
It would be great if the program expected that error and could continue to the next directory to attempt to clean - if it's not owned by current user then skip it, etc.

...
  File "/opt/python/3.9.4/lib/python3.9/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'stderr.log'

**Comment by bmwant** [comment]
@josht000 check if this error reproduces on the latest `0.7.0` version.
Besides that it includes feature allowing to set custom state directory. See [this](https://github.com/bmwant/hapless/blob/main/USAGE.md#%EF%B8%8F-state-directory) for the details.

**Comment by josht000** [comment]
@bmwant It doesn't crash (works) and simply says "nothing to clean". Could be a better message for this case in which there were some folders that couldn't be cleaned due to errors but it's good and works well :)


❯ hap
DEBUG:hapless:Initialized within /tmp/hapless dir
WARNING:hapless:Cannot find process: process PID not found (pid=53954)
┏━━━━┯━━━━━━━━━━━━┯━━━━━━━┯━━━━━━━━━━━┯━━━━┯━━━━━━━━━━┓
┃ #  │ Name       │ PID   │ Status    │ RC │  Runtime ┃
┠────┼────────────┼───────┼───────────┼────┼──────────┨
┃ 1  │ hap-f17vz5 │ 53954 │ • success │  0 │ a moment ┃
┗━━━━┷━━━━━━━━━━━━┷━━━━━━━┷━━━━━━━━━━━┷━━━━┷━━━━━━━━━━┛
❯ hap --version
DEBUG:hapless:Initialized within /tmp/hapless dir
hapless, version 0.7.0
❯ 
❯ 
❯ hapc
DEBUG:hapless:Initialized within /tmp/hapless dir
🧲 Nothing to clean
❯ haps
DEBUG:hapless:Initialized within /tmp/hapless dir
WARNING:hapless:Cannot find process: process PID not found (pid=53954)
┏━━━━┯━━━━━━━━━━━━┯━━━━━━━┯━━━━━━━━━━━┯━━━━┯━━━━━━━━━━┓
┃ #  │ Name       │ PID   │ Status    │ RC │  Runtime ┃
┠────┼────────────┼───────┼───────────┼────┼──────────┨
┃ 1  │ hap-f17vz5 │ 53954 │ • success │  0 │ a moment ┃
┗━━━━┷━━━━━━━━━━━━┷━━━━━━━┷━━━━━━━━━━━┷━━━━┷━━━━━━━━━━┛

**Comment by josht000** [comment]
@bmwant also, the TMPDIR env var works well. haven't tried the other new feature to set the state dir.

**Comment by josht000** [comment]
Closing as completed.
