### ISSUE TITLE
Question: stderr, log path, process name

### ISSUE THREAD

**Issue by d-ganchar** [bmwant/hapless#38]
Hello.

Thank you for your package 💛💙

I have a few questions:

- Is it possible to get `stderr` by `id`?
- Is it possible to set custom log path instead of `/tmp/hapless/...`?
- Is it possible to set custom name instead of `hap-...`? For example `hap run --name="copy_events_from_s3" ...`?

Best regards

**Comment by bmwant** [comment]
Hey @d-ganchar 

1. yes, to get stderr by id use
```bash
$ hap run python ./examples/fail_fast.py
$ hap logs -e 3
This script just fails
```

2. yes, but with a bit of a hack. State is designed to be ephemeral (as pids got reused between restarts, so directory is picked by [tempfile module](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir)). You can specify
```bash
export TMPDIR=/usr/tmp/dir
export HAPLESS_DEBUG=1  # enable debug info

hap
DEBUG:hapless:Initialized within /usr/tmp/dir/hapless dir
# ^^ willl show you path to the state directory
```
Therefore all the logs will be stored within specified directory.
In the future it will be supported by setting `HAPLESS_STATE_DIR`.


3. yes, with the command that you provided it should work
![Screenshot 2024-11-02 at 7 10 32 PM](https://github.com/user-attachments/assets/a201067d-3729-4ca2-886c-f2c064f42406)


For more details [check docs](https://github.com/bmwant/hapless/blob/main/USAGE.md)

**Comment by d-ganchar** [comment]
@bmwant thank you my friend ❤️
