### ISSUE TITLE
BUG: --user install error

### ISSUE THREAD

**Issue by josht000** [bmwant/hapless#42]
Can't find site packages, but the user option should still be available to install the hap temp directory in the user's home folder, not /tmp/hapless through this method or similar. Maybe hapless should never use /tmp/hapless?

```
❯ pip install --user hapless
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

❯ python -m pip install --user hapless
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

**Comment by bmwant** [comment]
@josht000 if possible, please provide details about your environment
```bash
# operating system used, e.g. with
uname -a
# python and pip version
python --version
pip --version
# details on the user and virtual environment
echo $HOME
echo $USER
echo $VIRTUAL_ENV
```

**Comment by josht000** [comment]
@bmwant Thanks,


```
❯ uname -a
Linux HOSTNAME 5.15.0-1040-nvidia #40-Ubuntu SMP Fri Oct 13 16:17:27 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
❯ python -V
Python 3.9.4
❯ echo $HOME
/home/NAME
❯ echo $USER
NAME
```

**Comment by bmwant** [comment]
You haven't shared your pip version and virtualenvironment env variable, but most likely it's due to some virtualenv being active.
Try
```bash
deactivate
# or
pyenv deactivate
# and then only
pip install --user hapless
```

See details why `--user` doesn't work within virtualenv [here](https://pip.pypa.io/en/stable/user_guide/#user-installs)

**Comment by josht000** [comment]
Oops, I forgot those 2. 

```
❯ echo $VIRTUAL_ENV
/home/NAME/envs/ngsri_training2

❯ pip --version
pip 20.2.3 from /home/NAME/envs/ENV/lib/python3.9/site-packages/pip (python 3.9)

❯ deactivate

❯ pip install --user hapless
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
I tried the deactivate command and the `pip install --user hapless` still same problem. 

pip 20.2.3 from /home/thamesj/envs/ngsri_training2/lib/python3.9/site-packages/pip (python 3.9)

Really I just want to change the **temp directory for hapless to be in my home folder, not /tmp/hapless** because other users on this machine (bare metal OS) also use hapless.

**Comment by josht000** [comment]
if there could be a .haprc file that I could configure it that'd be nice.

**Comment by bmwant** [comment]
If you goal to change state directory, you can use a workaround for now, see https://github.com/bmwant/hapless/issues/38

**Comment by josht000** [comment]
Ok, I think those work arounds from #38 did the trick. 
* VS code was adding to my env so had to ssh into the machine via a normal terminal
* TMP dir must exist, hapless won't create its own tmp dir if it doesn't exit :( 
* Added the `/home/NAME/.local/bin` to my path
* all is well 👍 

Thanks!
Josh
