### ISSUE TITLE
How to Remove the Failed Processes/Only keep the running ones?

### ISSUE THREAD

**Issue by ZihanChen1995** [bmwant/hapless#5]
Hi, thank you for this great package.

***May I ask can we remove/clear the failed processes, but only display the running ones, when using*** `hap`?

I have this question because, after killed and restarted the scripts, all the historical processes (failed/success/running) will be displayed on the `hat` status interface. However, we do not need to check the status of failed(i.e. killed) ones.

Can we only display the running ones through `hat`? Are there any options of it? 

Thank you so much!

**Comment by bmwant** [comment]
Hi @ZihanChen1995 ,
yes, you can run `hap clean` to remove all the finished processes.
![Screenshot from 2022-09-13 22-38-27](https://user-images.githubusercontent.com/3602533/190004699-49a2e6d4-9f38-4c68-be8f-d648ede798a2.png)

**Comment by bmwant** [comment]
Need to add that to the usage docs https://github.com/bmwant/hapless/blob/main/USAGE.md
Otherwise you can run `hap --help` to see all the available options

```bash
Commands:
  clean   Remove finished haps
  kill    Terminate a specific hap / all haps
  logs    Output logs for a hap
  pause   Pause a specific hap
  resume  Resume execution of a paused hap
  run     Execute background command as a hap
  show    Same as a status
  signal  Send an arbitrary signal to a hap
  status  Display information about haps

```

**Comment by ZihanChen1995** [comment]
Perfectly solved. Thank you so much!!
