### ISSUE TITLE
Install/build without using pip

### ISSUE THREAD

**Issue by graysky2** [bmwant/hapless#6]
How can I build/install this without using pip?  I have the dependencies on my system already.

**Comment by bmwant** [comment]
Currently there are no packages published besides PyPI (if you are asking about `.deb` or something similar).

**Comment by bmwant** [comment]
@graysky2 are you asking about ability to download artifact and install it like this?
```bash
$ curl <artifact-url>
$ tar -xvzf hapless-0.1.5.tar.gz
$ cd hapless-0.1.5
$ python setup.py install
```
?

**Comment by return42** [comment]
.. or is it unclear what pip does?

>  I have the dependencies on my system already.

if the dependencies installed on your system meets the conditions:

https://github.com/bmwant/hapless/blob/21738ef88311c3db49e0fdb15a6cc663652285c5/pyproject.toml#L28-L34

pip won't install them *again*.

**Comment by bmwant** [comment]
That's how I do it on Ubuntu

```
$ curl -O https://files.pythonhosted.org/packages/e4/07/d55c45db6909af8dee49d179ca500f31e249a67ff9a29385dc874b3817ed/hapless-0.1.5.tar.gz
$ tar -xvzf hapless-0.1.5.tar.gz
$ cd hapless-0.1.5 
$ python setup.py install
```

You need to download release from here https://pypi.org/project/hapless/#files or choose different version in order to have `setup.py` file. Currently I use [Poetry](https://python-poetry.org/) for the build/packaging that's why when downloading source code directly this file is missing.

**Comment by bmwant** [comment]
There is a plan to attach artifacts (archive `.tar.gz` and wheel `.whl`) to github releases / assets, but currently only downloading from PyPI is an option.

**Comment by graysky2** [comment]
OK, I will keep an eye out for that.

**Comment by bmwant** [comment]
@graysky2 hey, now it's possible to download artifacts from Github releases assets
```bash
$ curl -SLO https://github.com/bmwant/hapless/releases/download/v0.1.9/hapless-0.1.9.tar.gz
$ tar -xvzf hapless-0.1.9.tar.gz
$ cd hapless-0.1.9
$ python setup.py installl
```
You can also download wheel file and move package files / edit PATH / create symlink manually
```bash
$ curl -SLO https://github.com/bmwant/hapless/releases/download/v0.1.9/hapless-0.1.9-py3-none-any.whl
$ tar -xvzf hapless-0.1.9-py3-none-any.whl
x hapless/__init__.py
x hapless/cli.py
x hapless/config.py
x hapless/hap.py
x hapless/main.py
x hapless/utils.py
x hapless-0.1.9.dist-info/entry_points.txt
x hapless-0.1.9.dist-info/WHEEL
x hapless-0.1.9.dist-info/METADATA
x hapless-0.1.9.dist-info/RECORD
```
