### ISSUE TITLE
[Feature] Capture `stdout` and `stderr` and display it in the status

### ISSUE THREAD

**Issue by CaedenPH** [bmwant/hapless#8]
If a process fails, it would be useful for the user to see the `stdout` and `stderr`. How about capturing this in the process and piping it to a logs file
`systemctl` captures `stderr` and `stdout` and can be viewed via `journalctl`

**Comment by bmwant** [comment]
@CaedenPH it's possible to see both `stdout` / `stderr` of the process. Example

```bash
$ hap run python ./examples/fail_fast.py -n fail
$ hap status fail
$ hap show fail -v  # will print path to both stdout / stderr

$ hap logs fail  # will show stdout
$ hap logs --stderr fail  # will show stderr
```

**Comment by bmwant** [comment]
![image](https://user-images.githubusercontent.com/3602533/200172559-6325fb7d-e280-4aaa-8f1f-fb22d34a23d5.png)
Here's an example for the simple process that fails and has both stdout/stderr

**Comment by CaedenPH** [comment]
@bmwant Awesome! This repository is amazing, great work
