### ISSUE TITLE
[Feature] Shorten hap name / use string distance algorithm

### ISSUE THREAD

**Issue by CaedenPH** [bmwant/hapless#9]
It's a bit arduous having to type out the full hap name, when there is an unlikely chance of having `26**6` hap processes.
Perhaps the name could be shortened to `26**2` which still allows for 512 processes, or even `26**3` which is more than enough

Another option is using an algorithm such as 
https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by bmwant** [comment]
It's possible to 
a) provide `--name` flag when running a hap (or `-n`) to specify custom name/alias and then `hap status myname`
b) address each process/hap by its serial number (id): `hap status 1`
It's not required to manually type this random ID each time. I'm also thinking about adding shell completion, so this is not to be changed.
Thanks for the feature suggestion 👍
